In [57]:
import pandas as pd
import json
import ast

In [66]:
df = pd.read_json("000000Z.json")
# df_1 = pd.read_csv("operations.csv.gz")

In [67]:
pd.options.display.max_columns=None

In [1]:
import time

In [11]:
for i in range (0,40,5):
    time = ("00000" + str(i))[-6:]
    print(time)

000000
000005
000010
000015
000020
000025
000030
000035

In [14]:
for i in range(0, 100, 5):
    time = f"{i:06d}"  # Formatowanie liczby jako 6-cyfrowy string
    print(time, "->", time[-6:])  # Pobieramy ostatnie 3 cyfry

000000 -> 000000
000005 -> 000005
000010 -> 000010
000015 -> 000015
000020 -> 000020
000025 -> 000025
000030 -> 000030
000035 -> 000035
000040 -> 000040
000045 -> 000045
000050 -> 000050
000055 -> 000055
000060 -> 000060
000065 -> 000065
000070 -> 000070
000075 -> 000075
000080 -> 000080
000085 -> 000085
000090 -> 000090
000095 -> 000095

In [70]:
df_expanded = df.join(pd.json_normalize(df["aircraft"], sep="_"), rsuffix="_json")

# Usunięcie oryginalnej kolumny "aircraft"
df_expanded.drop(columns=["aircraft"], inplace=True)

df_expanded

,now,messages,hex,type,flight,r,t,alt_baro,gs,track,baro_rate,squawk,category,lat,lon,nic,rc,seen_pos,version,mlat,tisb,messages_json,seen,rssi,alt_geom,nav_qnh,nav_altitude_mcp,nav_heading,nic_baro,nac_p,nac_v,sil,sil_type,gva,sda,alert,spi,geom_rate,emergency,nav_modes,true_heading,dbFlags,mag_heading,ias,mach,tas,wd,ws,oat,tat,track_rate,roll,nav_altitude_fms,calc_track,gpsOkBefore,gpsOkLat,gpsOkLon,rr_lat,rr_lon,lastPosition_lat,lastPosition_lon,lastPosition_nic,lastPosition_rc,lastPosition_seen_pos
0,1.735690e+09,1112492492,86d244,other,ANA101,JA813A,B788,39975,476.0,248.00,0.0,4170,A5,59.494690,-172.154816,0.0,0.0,2.083,2.0,[],[],27797714,2.1,-49.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.735690e+09,1112492492,a1d8fd,other,UAL837,N218UA,B772,36000,481.0,263.00,0.0,6203,NaN,55.927860,-171.159698,0.0,0.0,2.083,NaN,[],[],49377812,2.1,-49.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.735690e+09,1112492492,a670a3,adsb_icao,DAL7,N514DN,A359,40000,485.5,250.26,0.0,NaN,A5,58.568848,-170.163161,8.0,186.0,3.454,2.0,[],[],43713704,0.0,-29.7,38750.0,1013.6,40000.0,239.06,1.0,9.0,2.0,3.0,perhour,2.0,2.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.735690e+09,1112492492,a92d6d,other,UAL79,N69020,B772,37000,469.0,244.00,0.0,1753,A5,59.133499,-169.464294,0.0,0.0,2.134,2.0,[],[],50287264,2.1,-49.5,35800.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.735690e+09,1112492492,780ff1,adsb_icao,CHH7926,B-7880,B789,37975,467.9,284.48,NaN,6751,A5,64.055740,-167.715278,8.0,186.0,0.617,2.0,[],[],17243330,0.6,-17.6,36775.0,1012.8,38016.0,270.70,1.0,9.0,1.0,3.0,perhour,2.0,2.0,0.0,0.0,0.0,none,"[autopilot, vnav, lnav, tcas]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10146,1.735690e+09,1112492492,ab9e12,mode_s,FDX3709,N848FD,B77L,ground,NaN,NaN,NaN,NaN,A5,NaN,NaN,NaN,NaN,NaN,0.0,[],[],43177966,3.2,-19.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,perhour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.676765,-74.183823,8.0,186.0,1819.212
10147,1.735690e+09,1112492492,81ff22,mode_s,NaN,NaN,NaN,ground,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,[],[],2,35.4,-49.5,NaN,NaN,NaN,NaN,NaN,10.0,NaN,2.0,unknown,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10148,1.735690e+09,1112492492,94940a,mode_s,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,[],[],2,3.2,-49.5,4300.0,NaN,NaN,NaN,NaN,11.0,NaN,2.0,unknown,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10149,1.735690e+09,1112492492,113421,mode_s,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,[],[],2,22.7,-49.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10150,1.735690e+09,1112492492,3742f2,mode_s,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,[],[],2,32.5,-49.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [82]:
str(df_expanded['mlat'][0])

'[]'

In [83]:
df_expanded[df_expanded['mlat'].astype(str) != '[]']

,now,messages,hex,type,flight,r,t,alt_baro,gs,track,baro_rate,squawk,category,lat,lon,nic,rc,seen_pos,version,mlat,tisb,messages_json,seen,rssi,alt_geom,nav_qnh,nav_altitude_mcp,nav_heading,nic_baro,nac_p,nac_v,sil,sil_type,gva,sda,alert,spi,geom_rate,emergency,nav_modes,true_heading,dbFlags,mag_heading,ias,mach,tas,wd,ws,oat,tat,track_rate,roll,nav_altitude_fms,calc_track,gpsOkBefore,gpsOkLat,gpsOkLon,rr_lat,rr_lon,lastPosition_lat,lastPosition_lon,lastPosition_nic,lastPosition_rc,lastPosition_seen_pos
70,1.735690e+09,1112492492,aa94ed,adsb_icao,HAL2,N781HA,B789,ground,0.0,242.00,0.0,3742,A5,21.306850,-157.945208,8.0,186.0,1.387,2.0,"[track, baro_rate]",[],30144308,1.4,-10.1,NaN,NaN,NaN,NaN,NaN,9.0,2.0,3.0,perhour,NaN,2.0,0.0,0.0,NaN,none,NaN,178.23,NaN,78.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,1.735690e+09,1112492492,a9fd3a,mlat,N7426Z,N7426Z,PA18,600,71.0,302.00,-76.0,1200,A1,61.266810,-150.000697,0.0,0.0,1.710,0.0,"[gs, track, baro_rate, lat, lon, nic, rc]",[],325281,0.9,-8.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,none,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
220,1.735690e+09,1112492492,a806d8,adsb_icao,UPS63,N616UP,B748,ground,12.8,117.00,0.0,4106,A5,61.174976,-149.997221,8.0,186.0,0.442,2.0,"[track, baro_rate]",[],44542466,0.4,-5.5,NaN,NaN,NaN,NaN,NaN,9.0,2.0,3.0,perhour,NaN,2.0,0.0,0.0,NaN,none,NaN,165.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223,1.735690e+09,1112492492,a7b07c,adsb_icao,FDX37,N595FE,MD11,ground,0.0,269.00,0.0,3355,A5,61.191567,-149.994736,8.0,186.0,2.624,2.0,"[track, baro_rate]",[],14202931,0.7,-6.1,NaN,NaN,NaN,NaN,NaN,8.0,1.0,3.0,perhour,NaN,2.0,0.0,0.0,NaN,none,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
380,1.735690e+09,1112492492,a6387e,mlat,N50KF,NaN,NaN,NaN,NaN,NaN,NaN,1200,NaN,45.941085,-122.792576,0.0,0.0,1.144,NaN,"[callsign, squawk, lat, lon, nic, rc]",[],242327,0.7,-12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,339.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8622,1.735690e+09,1112492492,7c6a8d,adsb_icao,VOZ1139,VH-VBZ,B737,ground,26.5,168.75,0.0,1473,A0,-33.962022,151.189528,8.0,186.0,0.264,0.0,[baro_rate],[],75476749,0.2,-15.1,NaN,NaN,NaN,NaN,NaN,8.0,NaN,2.0,unknown,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8627,1.735690e+09,1112492492,7cf7cb,mlat,SSM2,SSM2,TWR,ground,11.0,117.00,NaN,7722,NaN,-33.870679,151.209044,0.0,0.0,1.331,NaN,"[gs, track, lat, lon, nic, rc]",[],128964253,0.7,-7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8628,1.735690e+09,1112492492,7cf7ca,mlat,SSM1,SSM1,TWR,ground,26.0,87.00,NaN,7712,NaN,-33.870155,151.209453,0.0,0.0,0.412,NaN,"[gs, track, squawk, lat, lon, nic, rc]",[],115186128,0.1,-9.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8639,1.735690e+09,1112492492,7c5e61,mlat,NaN,VH-SXF,C208,1100,163.0,26.00,-2431.0,3000,NaN,-33.607123,151.310819,0.0,0.0,8.224,NaN,"[gs, track, baro_rate, lat, lon, nic, rc]",[],6399891,0.8,-19.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8695,1.735690e+09,1112492492,7cf7c8,mlat,NaN,SSM5,TWR,NaN,8.0,45.00,NaN,NaN,NaN,-27.387845,153.116424,0.0,0.0,0.056,NaN,"[gs, track, lat, lon, nic, rc]",[],24754634,0.0,-13.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
df.explode('aircraft')

                now    messages  aircraft
0      1.735690e+09  1112492492       hex
0      1.735690e+09  1112492492      type
0      1.735690e+09  1112492492    flight
0      1.735690e+09  1112492492         r
0      1.735690e+09  1112492492         t
...             ...         ...       ...
10150  1.735690e+09  1112492492      mlat
10150  1.735690e+09  1112492492      tisb
10150  1.735690e+09  1112492492  messages
10150  1.735690e+09  1112492492      seen
10150  1.735690e+09  1112492492      rssi

[325235 rows x 3 columns]

In [ ]:
"https://samples.adsbexchange.com/readsb-hist/2025/01/01/000000Z.json.gz"